# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

variables:
  hugo_version: "0.58.2"

jobs:
- job: build
  pool:
    vmImage: 'windows-latest'

  steps:
  - checkout: self
    displayName: 'Checkout repository including submodules'
    submodules: true  # true so Hugo theme submodule is checked out

  - task: HugoTask@1
    displayName: 'Build site with Hugo'
    inputs:
      destination: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: 'website'
    displayName: "Publish build"
    condition: succeeded()

- job: deploy
  dependsOn:
  - build
  condition: |
    and(
    false, and(
      succeeded('build'),
      and(
        not(eq(variables['Build.Reason'], 'PullRequest')),
        eq(variables['Build.SourceBranch'], 'refs/heads/master')
      )
    )
    )
  pool:
    vmImage: 'ubuntu-latest'
  workspace:
    clean: 'resources'  # Clear all the created content and downloaded repo information

  steps:
  - script: |
      git config --local user.name "lucianopaz"
      git config --local user.email $(github_email)
      git add docs/html
      git commit -m "Publishing GitHub Pages  ***NO_CI***"
    displayName: 'Commit built documentation'
    condition: succeeded()

  - task: InstallSSHKey@0
    name: install_sshkey
    inputs:
      knownHostsEntry: "github.com"
      sshPublicKey: $(sshpublicDeployKey)
      sshKeySecureFile: github_website_deploy_key
      sshPassphrase: $(passphrase)
    displayName: "Install repository's deploy key"
    condition: succeeded()

  - script: |
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    name: register_known_hosts
    displayName: "Register github as known host"
    condition: succeeded()